site_name: MTAV - 多轨道视频生成器
site_url: http://open.zhiyanxx.com/
nav:
    - 介绍:
        - MTAV介绍: index.md
        - 编译和安装: install.md
        - 快速开始: quick-start.md
        - 贡献和捐赠: contribute.md
    - 配置文件: 
        - 配置文件概述: config-file.md
        - 基础属性配置: base-config.md
        - 轨道配置: tracker-config.md
        - 插值器: interpolator.md
    - 基本轨道类型: 
        - 简单图像轨道: simple-image.md
        - 简单视频轨道: simple-video.md
    - 配置文件示例: 
        - 漂浮LOGO: examle-animation-logo.md

theme: readthedocs

